#pragma once

DEFINE_GUID(LOGITECH_XU_DEVICE_INFORMATION, 0x69678EE4, 0x410F, 0x40DB, 0xA8, 0x50, 0x74, 0x20, 0xD7, 0xD8, 0x24, 0x0E);
DEFINE_GUID(LOGITECH_XU_VIDEOPIPE_CONTROL, 0x49E40215, 0xF434, 0x47FE, 0xB1, 0x58, 0x0E, 0x88, 0x50, 0x23, 0xE5, 0x1B);
DEFINE_GUID(LOGITECH_XU_TEST_DEBUG, 0x1F5D4CA9, 0xDE11, 0x4487, 0x84, 0x0D, 0x50, 0x93, 0x3C, 0x8E, 0xC8, 0xD1);
DEFINE_GUID(LOGITECH_XU_PERIPHERAL_CONTROL, 0xFFE52D21, 0x8030, 0x4E2C, 0x82, 0xD9, 0xF5, 0x87, 0xD0, 0x05, 0x40, 0xBD);

enum //LOGITECH_XU_DEVICE_INFORMATION
{
	XU_DEVICE_INFORMATION_UNDEFINED_CONTROL = 0x00,
	XU_FIRMWARE_VERSION_CONTROL = 0x01,
	XU_FIRMWARE_CRC_CONTROL = 0x02,
	XU_EEPROM_VERSION_CONTROL = 0x03,
	XU_SENSOR_INFORMATION_CONTROL = 0x04,
	XU_PROCESSOR_INFORMATION_CONTROL = 0x05,
	XU_USB_INFORMATION_CONTROL = 0x06,
	XU_Reserved1 = 0x07,
	XU_Reserved2 = 0x08,
	XU_LENS_FOV_CONTROL = 0x09,
	XU_SENSOR_DIMENSION_CONTROL = 0x0A,
	XU_EXTENDED_FIRMWARE_VERSION_CONTROL = 0x0B,
};

enum //LOGITECH_XU_VIDEOPIPE_CONTROL
{
	XU_VIDEO_UNDEFINED_CONTROL = 0x00,
	XU_VIDEO_COLOR_BOOST_CONTROL = 0x01,
	XU_VIDEO_NATIVE_MODE_FORCED_CONTROL = 0x02,
	XU_VIDEO_NATIVE_MODE_AUTO_CONTROL = 0x03,
	XU_VIDEO_RIGHTLIGHT_MODE_CONTROL = 0x04,
	XU_VIDEO_RIGHTLIGHT_ZOI_CONTROL = 0x05,
	XU_VIDEO_FW_ZOOM_CONTROL = 0x06,
	XU_VIDEO_DUAL_ISO_ENABLE_CONTROL = 0x07,
	XU_VIDEO_SENSOR_CROPPING_DIMENSION_CONTROL = 0x08,
	XU_VIDEO_MJPEG_RESYNC_MARKER_CONTROL = 0x09,
	XU_VIDEO_ADVANCE_DIGITAL_ZOOM_CONTROL = 0x0A,
	XU_VIDEO_MJPEG_COMPRESS_RATIO_CONTROL = 0x0B,
	XU_VIDEO_HDR_CONTROL = 0x0C,
};

enum //LOGITECH_XU_TEST_DEBUG
{
	XU_TESTDEBUG_UNDEFINED_CONTROL = 0x00,
	XU_TEST_REGISTER_ADDRESS_CONTROL = 0x01,
	XU_TEST_REGISTER_ACCESS_CONTROL = 0x02,
	XU_TEST_EEPROM_ADDRESS_CONTROL = 0x03,
	XU_TEST_EEPROM_ACCESS_CONTROL = 0x04,
	XU_TEST_SENSOR_ADDRESS_CONTROL = 0x05,
	XU_TEST_SENSOR_ACCESS_CONTROL = 0x06,
	XU_PERIPHERAL_MODE_CONTROL = 0x07,
	XU_PERIPHERAL_OP_CONTROL = 0x08,
	XU_PERIPHERAL_ACCESS_CONTROL = 0x09,
	XU_TEST_TDE_MODE_CONTROL = 0x0A,
	XU_TEST_GAIN_ACCESS_CONTROL = 0x0B,
	XU_TEST_LOW_LIGHT_PRIORITY_CONTROL = 0x0C,
	XU_TEST_COLOR_PROCESSING_DISABLE_CONTROL = 0x0D,
	XU_TEST_PIXEL_DEFECT_CORRECTION_CONTROL = 0x0E,
	XU_TEST_LENS_SHADING_COMPENSATION_CONTROL = 0x0F,
	XU_TEST_GAMMA_CONTROL = 0x10,
	XU_TEST_INTEGRATION_TIME_CONTROL = 0x11,
	XU_TEST_RAW_DATA_BITS_PER_PIXEL_CONTROL = 0x12,
	XU_TEST_ISP_ADDRESS_CONTROL = 0x13,
	XU_TEST_ISP_ACCESS_CONTROL = 0x14,
	XU_PERIPHERAL_ACCESS_EXT_CONTROL = 0x15,
	XU_H264_FRAME_NO_CONTROL = 0x16,

};

// Seams that only 2 modes are defined for the PTZ Pro 2
//   XU_PERIPHERALCONTROL_PANTILT_RELATIVE_CONTROL  = pan tilt
//   XU_PERIPHERALCONTROL_PANTILT_MODE_CONTROL = Preset and recall position
enum //LOGITECH_XU_PERIPHERAL_CONTROL
{
	XU_PERIPHERAL_UNDEFINED_CONTROL = 0x00,
	XU_PERIPHERALCONTROL_PANTILT_RELATIVE_CONTROL = 0x01,							// pan tilt
	XU_PERIPHERALCONTROL_PANTILT_MODE_CONTROL = 0x02,								// Preset and recall position
	XU_PERIPHERALCONTROL_MAXIMUM_RESOLUTION_SUPPORT_FOR_PANTILT_CONTROL = 0x03,		
	XU_PERIPHERALCONTROL_AF_MOTORCONTROL = 0x04,
	XU_PERIPHERALCONTROL_AF_BLOB_CONTROL = 0x05,
	XU_PERIPHERALCONTROL_AF_VCM_PARAMETERS = 0x06,
	XU_PERIPHERALCONTROL_AF_STATUS = 0x07,
	XU_PERIPHERALCONTROL_AF_THRESHOLDS = 0x08,
	XU_PERIPHERALCONTROL_LED = 0x09,
	XU_PERIPHERAL_CONTROL_PERIPHERAL_STATUS = 0x0A,
	XU_PERIPHERAL_CONTROL_SPEAKER_VOLUME = 0x0B,
	XU_PERIPHERAL_CONTROL_DEVICE_CODEC_STATUS = 0x0C,
	XU_PERIPHERAL_CONTROL_SPEAKER = 0x0D,
	XU_PERIPHERAL_CONTROL_MODE = 0x0E,
	XU_AUDIO_LIBRARY_MODE_CONTROL = 0x0F,
	XU_PERIPHERAL_MOTOR_STEPS_CONTROL = 0x10,										

};


typedef enum
{
	XU_DEVICE_INFORMATION,
	XU_VIDEOPIPE_CONTROL,
	XU_TEST_DEBUG,
	XU_PERIPHERAL_CONTROL,
} LOGITECH_XU_PROPERTYSET;

/**
* Preset enumerations
*/
enum
{
	RESET_NOACTION = 0,
	SET_PRESET = 1,
	GOTO_PRESET = 2,
	GOTOHOME = 3
};

// enum
// {
// 	RESET_NOACTION = 0,
// 	RESET_PAN = 1,
// 	RESET_TILT = 2,
// };

